language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0
android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - addon-google_apis-google-$ANDROID_API_LEVEL
    
before_install:
 - chmod +x gradlew

script:
 - ./gradlew build connectedCheck
